set -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g mouse on

unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

set-option -g status-right ""
set-option -g status-style bg=#262626,fg=#cccccc
set-option -g window-status-style bg=#262626,fg=#cccccc
set-option -g window-status-current-style bg=#cccccc,fg=#262626
